version: "3.8"

services:
  generate-date:
    build: date-generate
    container_name: generate-date
    volumes:
      - index:/date
  web:
    image: nginx:1.19-alpine
    container_name: web1-compose
    depends_on:
      - generate-date
    ports:
      - 8080:80
    volumes:
      - index:/usr/share/nginx/html
volumes:
  index: